[package]
name = "particle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/particle.rs"

[dependencies]
piston2d-graphics = "0.43.0"
piston_window = "0.127.0"
rand = "0.8.5"
