load(":cmake.bzl", "run_cmake", "run_cmake2")
run_cmake(
    name = "run_cmake",
    cmake_project_path = "/home/shenda/bazel/bazel_cmake/test_bin",
    output = "cmake.log",
)
run_cmake2(
    name = "run_cmake2",
    cmake_project_path = "/home/shenda/bazel/bazel_cmake/test_bin",
)
