[package]
name = 'meminfo'
version = '0.1.0'
edition = '2021'

[lib]
path = 'src/meminfo-win32.rs'

[dependencies.winapi]
version = '0.3.9'
features = [
    'winnt',
    'sysinfoapi',
    'processthreadsapi',
    'memoryapi',
]
