/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: amessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "amessage.pb-c.h"
void   test__protobuf__c__submessage1__init
                     (Test__Protobuf__C__Submessage1         *message)
{
  static const Test__Protobuf__C__Submessage1 init_value = TEST__PROTOBUF__C__SUBMESSAGE1__INIT;
  *message = init_value;
}
size_t test__protobuf__c__submessage1__get_packed_size
                     (const Test__Protobuf__C__Submessage1 *message)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test__protobuf__c__submessage1__pack
                     (const Test__Protobuf__C__Submessage1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test__protobuf__c__submessage1__pack_to_buffer
                     (const Test__Protobuf__C__Submessage1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test__Protobuf__C__Submessage1 *
       test__protobuf__c__submessage1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test__Protobuf__C__Submessage1 *)
     protobuf_c_message_unpack (&test__protobuf__c__submessage1__descriptor,
                                allocator, len, data);
}
void   test__protobuf__c__submessage1__free_unpacked
                     (Test__Protobuf__C__Submessage1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test__protobuf__c__submessage1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test__protobuf__c__submessage2__init
                     (Test__Protobuf__C__Submessage2         *message)
{
  static const Test__Protobuf__C__Submessage2 init_value = TEST__PROTOBUF__C__SUBMESSAGE2__INIT;
  *message = init_value;
}
size_t test__protobuf__c__submessage2__get_packed_size
                     (const Test__Protobuf__C__Submessage2 *message)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test__protobuf__c__submessage2__pack
                     (const Test__Protobuf__C__Submessage2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test__protobuf__c__submessage2__pack_to_buffer
                     (const Test__Protobuf__C__Submessage2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test__protobuf__c__submessage2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test__Protobuf__C__Submessage2 *
       test__protobuf__c__submessage2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test__Protobuf__C__Submessage2 *)
     protobuf_c_message_unpack (&test__protobuf__c__submessage2__descriptor,
                                allocator, len, data);
}
void   test__protobuf__c__submessage2__free_unpacked
                     (Test__Protobuf__C__Submessage2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test__protobuf__c__submessage2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   test__protobuf__c__amessage__init
                     (Test__Protobuf__C__AMessage         *message)
{
  static const Test__Protobuf__C__AMessage init_value = TEST__PROTOBUF__C__AMESSAGE__INIT;
  *message = init_value;
}
size_t test__protobuf__c__amessage__get_packed_size
                     (const Test__Protobuf__C__AMessage *message)
{
  assert(message->base.descriptor == &test__protobuf__c__amessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test__protobuf__c__amessage__pack
                     (const Test__Protobuf__C__AMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &test__protobuf__c__amessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test__protobuf__c__amessage__pack_to_buffer
                     (const Test__Protobuf__C__AMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &test__protobuf__c__amessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Test__Protobuf__C__AMessage *
       test__protobuf__c__amessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test__Protobuf__C__AMessage *)
     protobuf_c_message_unpack (&test__protobuf__c__amessage__descriptor,
                                allocator, len, data);
}
void   test__protobuf__c__amessage__free_unpacked
                     (Test__Protobuf__C__AMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &test__protobuf__c__amessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor test__protobuf__c__submessage1__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__Protobuf__C__Submessage1, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test__protobuf__c__submessage1__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange test__protobuf__c__submessage1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test__protobuf__c__submessage1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test.protobuf.c.Submessage1",
  "Submessage1",
  "Test__Protobuf__C__Submessage1",
  "test.protobuf.c",
  sizeof(Test__Protobuf__C__Submessage1),
  1,
  test__protobuf__c__submessage1__field_descriptors,
  test__protobuf__c__submessage1__field_indices_by_name,
  1,  test__protobuf__c__submessage1__number_ranges,
  (ProtobufCMessageInit) test__protobuf__c__submessage1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test__protobuf__c__submessage2__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__Protobuf__C__Submessage2, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test__protobuf__c__submessage2__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange test__protobuf__c__submessage2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor test__protobuf__c__submessage2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test.protobuf.c.Submessage2",
  "Submessage2",
  "Test__Protobuf__C__Submessage2",
  "test.protobuf.c",
  sizeof(Test__Protobuf__C__Submessage2),
  1,
  test__protobuf__c__submessage2__field_descriptors,
  test__protobuf__c__submessage2__field_indices_by_name,
  1,  test__protobuf__c__submessage2__number_ranges,
  (ProtobufCMessageInit) test__protobuf__c__submessage2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor test__protobuf__c__amessage__field_descriptors[7] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test__Protobuf__C__AMessage, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Test__Protobuf__C__AMessage, has_b),
    offsetof(Test__Protobuf__C__AMessage, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Test__Protobuf__C__AMessage, n_c),
    offsetof(Test__Protobuf__C__AMessage, c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Test__Protobuf__C__AMessage, n_d),
    offsetof(Test__Protobuf__C__AMessage, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "e",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Test__Protobuf__C__AMessage, e),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Test__Protobuf__C__AMessage, f),
    &test__protobuf__c__submessage1__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Test__Protobuf__C__AMessage, n_g),
    offsetof(Test__Protobuf__C__AMessage, g),
    &test__protobuf__c__submessage2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test__protobuf__c__amessage__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
  2,   /* field[2] = c */
  3,   /* field[3] = d */
  4,   /* field[4] = e */
  5,   /* field[5] = f */
  6,   /* field[6] = g */
};
static const ProtobufCIntRange test__protobuf__c__amessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor test__protobuf__c__amessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "test.protobuf.c.AMessage",
  "AMessage",
  "Test__Protobuf__C__AMessage",
  "test.protobuf.c",
  sizeof(Test__Protobuf__C__AMessage),
  7,
  test__protobuf__c__amessage__field_descriptors,
  test__protobuf__c__amessage__field_indices_by_name,
  1,  test__protobuf__c__amessage__number_ranges,
  (ProtobufCMessageInit) test__protobuf__c__amessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
