//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MathLibrary {
  public static int add(int a, int b) {
    int ret = MathLibraryPINVOKE.add(a, b);
    return ret;
  }

  public static int subtract(int a, int b) {
    int ret = MathLibraryPINVOKE.subtract(a, b);
    return ret;
  }

}
