// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pointcloud.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pointcloud_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pointcloud_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pointcloud_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pointcloud_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pointcloud_2eproto;
namespace apollo {
namespace drivers {
class PointCloud;
class PointCloudDefaultTypeInternal;
extern PointCloudDefaultTypeInternal _PointCloud_default_instance_;
class PointCloudOpt;
class PointCloudOptDefaultTypeInternal;
extern PointCloudOptDefaultTypeInternal _PointCloudOpt_default_instance_;
class PointCloudRefine;
class PointCloudRefineDefaultTypeInternal;
extern PointCloudRefineDefaultTypeInternal _PointCloudRefine_default_instance_;
class PointXYZIT;
class PointXYZITDefaultTypeInternal;
extern PointXYZITDefaultTypeInternal _PointXYZIT_default_instance_;
class PointXYZITRefine;
class PointXYZITRefineDefaultTypeInternal;
extern PointXYZITRefineDefaultTypeInternal _PointXYZITRefine_default_instance_;
}  // namespace drivers
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::drivers::PointCloud* Arena::CreateMaybeMessage<::apollo::drivers::PointCloud>(Arena*);
template<> ::apollo::drivers::PointCloudOpt* Arena::CreateMaybeMessage<::apollo::drivers::PointCloudOpt>(Arena*);
template<> ::apollo::drivers::PointCloudRefine* Arena::CreateMaybeMessage<::apollo::drivers::PointCloudRefine>(Arena*);
template<> ::apollo::drivers::PointXYZIT* Arena::CreateMaybeMessage<::apollo::drivers::PointXYZIT>(Arena*);
template<> ::apollo::drivers::PointXYZITRefine* Arena::CreateMaybeMessage<::apollo::drivers::PointXYZITRefine>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace drivers {

// ===================================================================

class PointXYZIT PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.drivers.PointXYZIT) */ {
 public:
  inline PointXYZIT() : PointXYZIT(nullptr) {}
  virtual ~PointXYZIT();

  PointXYZIT(const PointXYZIT& from);
  PointXYZIT(PointXYZIT&& from) noexcept
    : PointXYZIT() {
    *this = ::std::move(from);
  }

  inline PointXYZIT& operator=(const PointXYZIT& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointXYZIT& operator=(PointXYZIT&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointXYZIT& default_instance();

  static inline const PointXYZIT* internal_default_instance() {
    return reinterpret_cast<const PointXYZIT*>(
               &_PointXYZIT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PointXYZIT& a, PointXYZIT& b) {
    a.Swap(&b);
  }
  inline void Swap(PointXYZIT* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointXYZIT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointXYZIT* New() const final {
    return CreateMaybeMessage<PointXYZIT>(nullptr);
  }

  PointXYZIT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointXYZIT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointXYZIT& from);
  void MergeFrom(const PointXYZIT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointXYZIT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.drivers.PointXYZIT";
  }
  protected:
  explicit PointXYZIT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pointcloud_2eproto);
    return ::descriptor_table_pointcloud_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 5,
    kIntensityFieldNumber = 4,
    kZFieldNumber = 3,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // optional uint64 timestamp = 5 [default = 0];
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint32 intensity = 4 [default = 0];
  bool has_intensity() const;
  private:
  bool _internal_has_intensity() const;
  public:
  void clear_intensity();
  ::PROTOBUF_NAMESPACE_ID::uint32 intensity() const;
  void set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_intensity() const;
  void _internal_set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float z = 3 [default = nan];
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // optional float x = 1 [default = nan];
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // optional float y = 2 [default = nan];
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.drivers.PointXYZIT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 intensity_;
  float z_;
  float x_;
  float y_;
  friend struct ::TableStruct_pointcloud_2eproto;
};
// -------------------------------------------------------------------

class PointCloud PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.drivers.PointCloud) */ {
 public:
  inline PointCloud() : PointCloud(nullptr) {}
  virtual ~PointCloud();

  PointCloud(const PointCloud& from);
  PointCloud(PointCloud&& from) noexcept
    : PointCloud() {
    *this = ::std::move(from);
  }

  inline PointCloud& operator=(const PointCloud& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointCloud& operator=(PointCloud&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointCloud& default_instance();

  static inline const PointCloud* internal_default_instance() {
    return reinterpret_cast<const PointCloud*>(
               &_PointCloud_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PointCloud& a, PointCloud& b) {
    a.Swap(&b);
  }
  inline void Swap(PointCloud* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointCloud* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointCloud* New() const final {
    return CreateMaybeMessage<PointCloud>(nullptr);
  }

  PointCloud* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointCloud>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointCloud& from);
  void MergeFrom(const PointCloud& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointCloud* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.drivers.PointCloud";
  }
  protected:
  explicit PointCloud(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pointcloud_2eproto);
    return ::descriptor_table_pointcloud_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 4,
    kFrameIdFieldNumber = 2,
    kHeaderFieldNumber = 1,
    kIsDenseFieldNumber = 3,
    kWidthFieldNumber = 6,
    kMeasurementTimeFieldNumber = 5,
    kHeightFieldNumber = 7,
  };
  // repeated .apollo.drivers.PointXYZIT point = 4;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::apollo::drivers::PointXYZIT* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >*
      mutable_point();
  private:
  const ::apollo::drivers::PointXYZIT& _internal_point(int index) const;
  ::apollo::drivers::PointXYZIT* _internal_add_point();
  public:
  const ::apollo::drivers::PointXYZIT& point(int index) const;
  ::apollo::drivers::PointXYZIT* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >&
      point() const;

  // optional string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);
  private:
  const ::apollo::common::Header& _internal_header() const;
  ::apollo::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::apollo::common::Header* header);
  ::apollo::common::Header* unsafe_arena_release_header();

  // optional bool is_dense = 3;
  bool has_is_dense() const;
  private:
  bool _internal_has_is_dense() const;
  public:
  void clear_is_dense();
  bool is_dense() const;
  void set_is_dense(bool value);
  private:
  bool _internal_is_dense() const;
  void _internal_set_is_dense(bool value);
  public:

  // optional uint32 width = 6;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional double measurement_time = 5;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional uint32 height = 7;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.drivers.PointCloud)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT > point_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::apollo::common::Header* header_;
  bool is_dense_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  double measurement_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  friend struct ::TableStruct_pointcloud_2eproto;
};
// -------------------------------------------------------------------

class PointCloudOpt PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.drivers.PointCloudOpt) */ {
 public:
  inline PointCloudOpt() : PointCloudOpt(nullptr) {}
  virtual ~PointCloudOpt();

  PointCloudOpt(const PointCloudOpt& from);
  PointCloudOpt(PointCloudOpt&& from) noexcept
    : PointCloudOpt() {
    *this = ::std::move(from);
  }

  inline PointCloudOpt& operator=(const PointCloudOpt& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointCloudOpt& operator=(PointCloudOpt&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointCloudOpt& default_instance();

  static inline const PointCloudOpt* internal_default_instance() {
    return reinterpret_cast<const PointCloudOpt*>(
               &_PointCloudOpt_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PointCloudOpt& a, PointCloudOpt& b) {
    a.Swap(&b);
  }
  inline void Swap(PointCloudOpt* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointCloudOpt* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointCloudOpt* New() const final {
    return CreateMaybeMessage<PointCloudOpt>(nullptr);
  }

  PointCloudOpt* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointCloudOpt>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointCloudOpt& from);
  void MergeFrom(const PointCloudOpt& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointCloudOpt* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.drivers.PointCloudOpt";
  }
  protected:
  explicit PointCloudOpt(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pointcloud_2eproto);
    return ::descriptor_table_pointcloud_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 2,
    kPointFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kIsDenseFieldNumber = 3,
    kWidthFieldNumber = 6,
    kMeasurementTimeFieldNumber = 5,
    kHeightFieldNumber = 7,
  };
  // optional string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // optional bytes point = 4;
  bool has_point() const;
  private:
  bool _internal_has_point() const;
  public:
  void clear_point();
  const std::string& point() const;
  void set_point(const std::string& value);
  void set_point(std::string&& value);
  void set_point(const char* value);
  void set_point(const void* value, size_t size);
  std::string* mutable_point();
  std::string* release_point();
  void set_allocated_point(std::string* point);
  private:
  const std::string& _internal_point() const;
  void _internal_set_point(const std::string& value);
  std::string* _internal_mutable_point();
  public:

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);
  private:
  const ::apollo::common::Header& _internal_header() const;
  ::apollo::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::apollo::common::Header* header);
  ::apollo::common::Header* unsafe_arena_release_header();

  // optional bool is_dense = 3;
  bool has_is_dense() const;
  private:
  bool _internal_has_is_dense() const;
  public:
  void clear_is_dense();
  bool is_dense() const;
  void set_is_dense(bool value);
  private:
  bool _internal_is_dense() const;
  void _internal_set_is_dense(bool value);
  public:

  // optional uint32 width = 6;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional double measurement_time = 5;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional uint32 height = 7;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.drivers.PointCloudOpt)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr point_;
  ::apollo::common::Header* header_;
  bool is_dense_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  double measurement_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  friend struct ::TableStruct_pointcloud_2eproto;
};
// -------------------------------------------------------------------

class PointXYZITRefine PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.drivers.PointXYZITRefine) */ {
 public:
  inline PointXYZITRefine() : PointXYZITRefine(nullptr) {}
  virtual ~PointXYZITRefine();

  PointXYZITRefine(const PointXYZITRefine& from);
  PointXYZITRefine(PointXYZITRefine&& from) noexcept
    : PointXYZITRefine() {
    *this = ::std::move(from);
  }

  inline PointXYZITRefine& operator=(const PointXYZITRefine& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointXYZITRefine& operator=(PointXYZITRefine&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointXYZITRefine& default_instance();

  static inline const PointXYZITRefine* internal_default_instance() {
    return reinterpret_cast<const PointXYZITRefine*>(
               &_PointXYZITRefine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PointXYZITRefine& a, PointXYZITRefine& b) {
    a.Swap(&b);
  }
  inline void Swap(PointXYZITRefine* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointXYZITRefine* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointXYZITRefine* New() const final {
    return CreateMaybeMessage<PointXYZITRefine>(nullptr);
  }

  PointXYZITRefine* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointXYZITRefine>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointXYZITRefine& from);
  void MergeFrom(const PointXYZITRefine& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointXYZITRefine* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.drivers.PointXYZITRefine";
  }
  protected:
  explicit PointXYZITRefine(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pointcloud_2eproto);
    return ::descriptor_table_pointcloud_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 5,
    kIntensityFieldNumber = 4,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // optional fixed64 timestamp = 5 [default = 0];
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional fixed32 intensity = 4 [default = 0];
  bool has_intensity() const;
  private:
  bool _internal_has_intensity() const;
  public:
  void clear_intensity();
  ::PROTOBUF_NAMESPACE_ID::uint32 intensity() const;
  void set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_intensity() const;
  void _internal_set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional double x = 1 [default = nan];
  bool has_x() const;
  private:
  bool _internal_has_x() const;
  public:
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // optional double y = 2 [default = nan];
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // optional double z = 3 [default = nan];
  bool has_z() const;
  private:
  bool _internal_has_z() const;
  public:
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.drivers.PointXYZITRefine)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint32 intensity_;
  double x_;
  double y_;
  double z_;
  friend struct ::TableStruct_pointcloud_2eproto;
};
// -------------------------------------------------------------------

class PointCloudRefine PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.drivers.PointCloudRefine) */ {
 public:
  inline PointCloudRefine() : PointCloudRefine(nullptr) {}
  virtual ~PointCloudRefine();

  PointCloudRefine(const PointCloudRefine& from);
  PointCloudRefine(PointCloudRefine&& from) noexcept
    : PointCloudRefine() {
    *this = ::std::move(from);
  }

  inline PointCloudRefine& operator=(const PointCloudRefine& from) {
    CopyFrom(from);
    return *this;
  }
  inline PointCloudRefine& operator=(PointCloudRefine&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PointCloudRefine& default_instance();

  static inline const PointCloudRefine* internal_default_instance() {
    return reinterpret_cast<const PointCloudRefine*>(
               &_PointCloudRefine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PointCloudRefine& a, PointCloudRefine& b) {
    a.Swap(&b);
  }
  inline void Swap(PointCloudRefine* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PointCloudRefine* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PointCloudRefine* New() const final {
    return CreateMaybeMessage<PointCloudRefine>(nullptr);
  }

  PointCloudRefine* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PointCloudRefine>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PointCloudRefine& from);
  void MergeFrom(const PointCloudRefine& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PointCloudRefine* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.drivers.PointCloudRefine";
  }
  protected:
  explicit PointCloudRefine(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pointcloud_2eproto);
    return ::descriptor_table_pointcloud_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointFieldNumber = 4,
    kFrameIdFieldNumber = 2,
    kHeaderFieldNumber = 1,
    kIsDenseFieldNumber = 3,
    kWidthFieldNumber = 6,
    kMeasurementTimeFieldNumber = 5,
    kHeightFieldNumber = 7,
  };
  // repeated .apollo.drivers.PointXYZIT point = 4;
  int point_size() const;
  private:
  int _internal_point_size() const;
  public:
  void clear_point();
  ::apollo::drivers::PointXYZIT* mutable_point(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >*
      mutable_point();
  private:
  const ::apollo::drivers::PointXYZIT& _internal_point(int index) const;
  ::apollo::drivers::PointXYZIT* _internal_add_point();
  public:
  const ::apollo::drivers::PointXYZIT& point(int index) const;
  ::apollo::drivers::PointXYZIT* add_point();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >&
      point() const;

  // optional string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);
  private:
  const ::apollo::common::Header& _internal_header() const;
  ::apollo::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::apollo::common::Header* header);
  ::apollo::common::Header* unsafe_arena_release_header();

  // optional bool is_dense = 3;
  bool has_is_dense() const;
  private:
  bool _internal_has_is_dense() const;
  public:
  void clear_is_dense();
  bool is_dense() const;
  void set_is_dense(bool value);
  private:
  bool _internal_is_dense() const;
  void _internal_set_is_dense(bool value);
  public:

  // optional fixed32 width = 6;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional double measurement_time = 5;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional fixed32 height = 7;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.drivers.PointCloudRefine)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT > point_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::apollo::common::Header* header_;
  bool is_dense_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  double measurement_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  friend struct ::TableStruct_pointcloud_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PointXYZIT

// optional float x = 1 [default = nan];
inline bool PointXYZIT::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PointXYZIT::has_x() const {
  return _internal_has_x();
}
inline void PointXYZIT::clear_x() {
  x_ = std::numeric_limits<float>::quiet_NaN();
  _has_bits_[0] &= ~0x00000008u;
}
inline float PointXYZIT::_internal_x() const {
  return x_;
}
inline float PointXYZIT::x() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZIT.x)
  return _internal_x();
}
inline void PointXYZIT::_internal_set_x(float value) {
  _has_bits_[0] |= 0x00000008u;
  x_ = value;
}
inline void PointXYZIT::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZIT.x)
}

// optional float y = 2 [default = nan];
inline bool PointXYZIT::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PointXYZIT::has_y() const {
  return _internal_has_y();
}
inline void PointXYZIT::clear_y() {
  y_ = std::numeric_limits<float>::quiet_NaN();
  _has_bits_[0] &= ~0x00000010u;
}
inline float PointXYZIT::_internal_y() const {
  return y_;
}
inline float PointXYZIT::y() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZIT.y)
  return _internal_y();
}
inline void PointXYZIT::_internal_set_y(float value) {
  _has_bits_[0] |= 0x00000010u;
  y_ = value;
}
inline void PointXYZIT::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZIT.y)
}

// optional float z = 3 [default = nan];
inline bool PointXYZIT::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PointXYZIT::has_z() const {
  return _internal_has_z();
}
inline void PointXYZIT::clear_z() {
  z_ = std::numeric_limits<float>::quiet_NaN();
  _has_bits_[0] &= ~0x00000004u;
}
inline float PointXYZIT::_internal_z() const {
  return z_;
}
inline float PointXYZIT::z() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZIT.z)
  return _internal_z();
}
inline void PointXYZIT::_internal_set_z(float value) {
  _has_bits_[0] |= 0x00000004u;
  z_ = value;
}
inline void PointXYZIT::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZIT.z)
}

// optional uint32 intensity = 4 [default = 0];
inline bool PointXYZIT::_internal_has_intensity() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PointXYZIT::has_intensity() const {
  return _internal_has_intensity();
}
inline void PointXYZIT::clear_intensity() {
  intensity_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointXYZIT::_internal_intensity() const {
  return intensity_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointXYZIT::intensity() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZIT.intensity)
  return _internal_intensity();
}
inline void PointXYZIT::_internal_set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  intensity_ = value;
}
inline void PointXYZIT::set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_intensity(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZIT.intensity)
}

// optional uint64 timestamp = 5 [default = 0];
inline bool PointXYZIT::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PointXYZIT::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void PointXYZIT::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PointXYZIT::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PointXYZIT::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZIT.timestamp)
  return _internal_timestamp();
}
inline void PointXYZIT::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_ = value;
}
inline void PointXYZIT::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZIT.timestamp)
}

// -------------------------------------------------------------------

// PointCloud

// optional .apollo.common.Header header = 1;
inline bool PointCloud::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool PointCloud::has_header() const {
  return _internal_has_header();
}
inline const ::apollo::common::Header& PointCloud::_internal_header() const {
  const ::apollo::common::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::common::Header&>(
      ::apollo::common::_Header_default_instance_);
}
inline const ::apollo::common::Header& PointCloud::header() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.header)
  return _internal_header();
}
inline void PointCloud::unsafe_arena_set_allocated_header(
    ::apollo::common::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.drivers.PointCloud.header)
}
inline ::apollo::common::Header* PointCloud::release_header() {
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::apollo::common::Header* PointCloud::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloud.header)
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::apollo::common::Header* PointCloud::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000002u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::apollo::common::Header* PointCloud::mutable_header() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloud.header)
  return _internal_mutable_header();
}
inline void PointCloud::set_allocated_header(::apollo::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloud.header)
}

// optional string frame_id = 2;
inline bool PointCloud::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PointCloud::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void PointCloud::clear_frame_id() {
  frame_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PointCloud::frame_id() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.frame_id)
  return _internal_frame_id();
}
inline void PointCloud::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloud.frame_id)
}
inline std::string* PointCloud::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloud.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& PointCloud::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void PointCloud::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PointCloud::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.drivers.PointCloud.frame_id)
}
inline void PointCloud::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.drivers.PointCloud.frame_id)
}
inline void PointCloud::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.drivers.PointCloud.frame_id)
}
inline std::string* PointCloud::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PointCloud::release_frame_id() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloud.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PointCloud::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloud.frame_id)
}

// optional bool is_dense = 3;
inline bool PointCloud::_internal_has_is_dense() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PointCloud::has_is_dense() const {
  return _internal_has_is_dense();
}
inline void PointCloud::clear_is_dense() {
  is_dense_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool PointCloud::_internal_is_dense() const {
  return is_dense_;
}
inline bool PointCloud::is_dense() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.is_dense)
  return _internal_is_dense();
}
inline void PointCloud::_internal_set_is_dense(bool value) {
  _has_bits_[0] |= 0x00000004u;
  is_dense_ = value;
}
inline void PointCloud::set_is_dense(bool value) {
  _internal_set_is_dense(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloud.is_dense)
}

// repeated .apollo.drivers.PointXYZIT point = 4;
inline int PointCloud::_internal_point_size() const {
  return point_.size();
}
inline int PointCloud::point_size() const {
  return _internal_point_size();
}
inline void PointCloud::clear_point() {
  point_.Clear();
}
inline ::apollo::drivers::PointXYZIT* PointCloud::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloud.point)
  return point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >*
PointCloud::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.drivers.PointCloud.point)
  return &point_;
}
inline const ::apollo::drivers::PointXYZIT& PointCloud::_internal_point(int index) const {
  return point_.Get(index);
}
inline const ::apollo::drivers::PointXYZIT& PointCloud::point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.point)
  return _internal_point(index);
}
inline ::apollo::drivers::PointXYZIT* PointCloud::_internal_add_point() {
  return point_.Add();
}
inline ::apollo::drivers::PointXYZIT* PointCloud::add_point() {
  // @@protoc_insertion_point(field_add:apollo.drivers.PointCloud.point)
  return _internal_add_point();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >&
PointCloud::point() const {
  // @@protoc_insertion_point(field_list:apollo.drivers.PointCloud.point)
  return point_;
}

// optional double measurement_time = 5;
inline bool PointCloud::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PointCloud::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void PointCloud::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double PointCloud::_internal_measurement_time() const {
  return measurement_time_;
}
inline double PointCloud::measurement_time() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.measurement_time)
  return _internal_measurement_time();
}
inline void PointCloud::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000010u;
  measurement_time_ = value;
}
inline void PointCloud::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloud.measurement_time)
}

// optional uint32 width = 6;
inline bool PointCloud::_internal_has_width() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PointCloud::has_width() const {
  return _internal_has_width();
}
inline void PointCloud::clear_width() {
  width_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloud::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloud::width() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.width)
  return _internal_width();
}
inline void PointCloud::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  width_ = value;
}
inline void PointCloud::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloud.width)
}

// optional uint32 height = 7;
inline bool PointCloud::_internal_has_height() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool PointCloud::has_height() const {
  return _internal_has_height();
}
inline void PointCloud::clear_height() {
  height_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloud::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloud::height() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloud.height)
  return _internal_height();
}
inline void PointCloud::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  height_ = value;
}
inline void PointCloud::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloud.height)
}

// -------------------------------------------------------------------

// PointCloudOpt

// optional .apollo.common.Header header = 1;
inline bool PointCloudOpt::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool PointCloudOpt::has_header() const {
  return _internal_has_header();
}
inline const ::apollo::common::Header& PointCloudOpt::_internal_header() const {
  const ::apollo::common::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::common::Header&>(
      ::apollo::common::_Header_default_instance_);
}
inline const ::apollo::common::Header& PointCloudOpt::header() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.header)
  return _internal_header();
}
inline void PointCloudOpt::unsafe_arena_set_allocated_header(
    ::apollo::common::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.drivers.PointCloudOpt.header)
}
inline ::apollo::common::Header* PointCloudOpt::release_header() {
  _has_bits_[0] &= ~0x00000004u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::apollo::common::Header* PointCloudOpt::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloudOpt.header)
  _has_bits_[0] &= ~0x00000004u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::apollo::common::Header* PointCloudOpt::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000004u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::apollo::common::Header* PointCloudOpt::mutable_header() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudOpt.header)
  return _internal_mutable_header();
}
inline void PointCloudOpt::set_allocated_header(::apollo::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloudOpt.header)
}

// optional string frame_id = 2;
inline bool PointCloudOpt::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PointCloudOpt::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void PointCloudOpt::clear_frame_id() {
  frame_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PointCloudOpt::frame_id() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.frame_id)
  return _internal_frame_id();
}
inline void PointCloudOpt::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.frame_id)
}
inline std::string* PointCloudOpt::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudOpt.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& PointCloudOpt::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void PointCloudOpt::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PointCloudOpt::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.drivers.PointCloudOpt.frame_id)
}
inline void PointCloudOpt::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.drivers.PointCloudOpt.frame_id)
}
inline void PointCloudOpt::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.drivers.PointCloudOpt.frame_id)
}
inline std::string* PointCloudOpt::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PointCloudOpt::release_frame_id() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloudOpt.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PointCloudOpt::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloudOpt.frame_id)
}

// optional bool is_dense = 3;
inline bool PointCloudOpt::_internal_has_is_dense() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PointCloudOpt::has_is_dense() const {
  return _internal_has_is_dense();
}
inline void PointCloudOpt::clear_is_dense() {
  is_dense_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool PointCloudOpt::_internal_is_dense() const {
  return is_dense_;
}
inline bool PointCloudOpt::is_dense() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.is_dense)
  return _internal_is_dense();
}
inline void PointCloudOpt::_internal_set_is_dense(bool value) {
  _has_bits_[0] |= 0x00000008u;
  is_dense_ = value;
}
inline void PointCloudOpt::set_is_dense(bool value) {
  _internal_set_is_dense(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.is_dense)
}

// optional bytes point = 4;
inline bool PointCloudOpt::_internal_has_point() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PointCloudOpt::has_point() const {
  return _internal_has_point();
}
inline void PointCloudOpt::clear_point() {
  point_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PointCloudOpt::point() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.point)
  return _internal_point();
}
inline void PointCloudOpt::set_point(const std::string& value) {
  _internal_set_point(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.point)
}
inline std::string* PointCloudOpt::mutable_point() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudOpt.point)
  return _internal_mutable_point();
}
inline const std::string& PointCloudOpt::_internal_point() const {
  return point_.Get();
}
inline void PointCloudOpt::_internal_set_point(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  point_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PointCloudOpt::set_point(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  point_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.drivers.PointCloudOpt.point)
}
inline void PointCloudOpt::set_point(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  point_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.drivers.PointCloudOpt.point)
}
inline void PointCloudOpt::set_point(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  point_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.drivers.PointCloudOpt.point)
}
inline std::string* PointCloudOpt::_internal_mutable_point() {
  _has_bits_[0] |= 0x00000002u;
  return point_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PointCloudOpt::release_point() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloudOpt.point)
  if (!_internal_has_point()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return point_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PointCloudOpt::set_allocated_point(std::string* point) {
  if (point != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  point_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), point,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloudOpt.point)
}

// optional double measurement_time = 5;
inline bool PointCloudOpt::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool PointCloudOpt::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void PointCloudOpt::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double PointCloudOpt::_internal_measurement_time() const {
  return measurement_time_;
}
inline double PointCloudOpt::measurement_time() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.measurement_time)
  return _internal_measurement_time();
}
inline void PointCloudOpt::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000020u;
  measurement_time_ = value;
}
inline void PointCloudOpt::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.measurement_time)
}

// optional uint32 width = 6;
inline bool PointCloudOpt::_internal_has_width() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PointCloudOpt::has_width() const {
  return _internal_has_width();
}
inline void PointCloudOpt::clear_width() {
  width_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudOpt::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudOpt::width() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.width)
  return _internal_width();
}
inline void PointCloudOpt::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  width_ = value;
}
inline void PointCloudOpt::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.width)
}

// optional uint32 height = 7;
inline bool PointCloudOpt::_internal_has_height() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool PointCloudOpt::has_height() const {
  return _internal_has_height();
}
inline void PointCloudOpt::clear_height() {
  height_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudOpt::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudOpt::height() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudOpt.height)
  return _internal_height();
}
inline void PointCloudOpt::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  height_ = value;
}
inline void PointCloudOpt::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudOpt.height)
}

// -------------------------------------------------------------------

// PointXYZITRefine

// optional double x = 1 [default = nan];
inline bool PointXYZITRefine::_internal_has_x() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PointXYZITRefine::has_x() const {
  return _internal_has_x();
}
inline void PointXYZITRefine::clear_x() {
  x_ = std::numeric_limits<double>::quiet_NaN();
  _has_bits_[0] &= ~0x00000004u;
}
inline double PointXYZITRefine::_internal_x() const {
  return x_;
}
inline double PointXYZITRefine::x() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZITRefine.x)
  return _internal_x();
}
inline void PointXYZITRefine::_internal_set_x(double value) {
  _has_bits_[0] |= 0x00000004u;
  x_ = value;
}
inline void PointXYZITRefine::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZITRefine.x)
}

// optional double y = 2 [default = nan];
inline bool PointXYZITRefine::_internal_has_y() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PointXYZITRefine::has_y() const {
  return _internal_has_y();
}
inline void PointXYZITRefine::clear_y() {
  y_ = std::numeric_limits<double>::quiet_NaN();
  _has_bits_[0] &= ~0x00000008u;
}
inline double PointXYZITRefine::_internal_y() const {
  return y_;
}
inline double PointXYZITRefine::y() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZITRefine.y)
  return _internal_y();
}
inline void PointXYZITRefine::_internal_set_y(double value) {
  _has_bits_[0] |= 0x00000008u;
  y_ = value;
}
inline void PointXYZITRefine::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZITRefine.y)
}

// optional double z = 3 [default = nan];
inline bool PointXYZITRefine::_internal_has_z() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PointXYZITRefine::has_z() const {
  return _internal_has_z();
}
inline void PointXYZITRefine::clear_z() {
  z_ = std::numeric_limits<double>::quiet_NaN();
  _has_bits_[0] &= ~0x00000010u;
}
inline double PointXYZITRefine::_internal_z() const {
  return z_;
}
inline double PointXYZITRefine::z() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZITRefine.z)
  return _internal_z();
}
inline void PointXYZITRefine::_internal_set_z(double value) {
  _has_bits_[0] |= 0x00000010u;
  z_ = value;
}
inline void PointXYZITRefine::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZITRefine.z)
}

// optional fixed32 intensity = 4 [default = 0];
inline bool PointXYZITRefine::_internal_has_intensity() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PointXYZITRefine::has_intensity() const {
  return _internal_has_intensity();
}
inline void PointXYZITRefine::clear_intensity() {
  intensity_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointXYZITRefine::_internal_intensity() const {
  return intensity_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointXYZITRefine::intensity() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZITRefine.intensity)
  return _internal_intensity();
}
inline void PointXYZITRefine::_internal_set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  intensity_ = value;
}
inline void PointXYZITRefine::set_intensity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_intensity(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZITRefine.intensity)
}

// optional fixed64 timestamp = 5 [default = 0];
inline bool PointXYZITRefine::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PointXYZITRefine::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void PointXYZITRefine::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PointXYZITRefine::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PointXYZITRefine::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointXYZITRefine.timestamp)
  return _internal_timestamp();
}
inline void PointXYZITRefine::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  timestamp_ = value;
}
inline void PointXYZITRefine::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointXYZITRefine.timestamp)
}

// -------------------------------------------------------------------

// PointCloudRefine

// optional .apollo.common.Header header = 1;
inline bool PointCloudRefine::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool PointCloudRefine::has_header() const {
  return _internal_has_header();
}
inline const ::apollo::common::Header& PointCloudRefine::_internal_header() const {
  const ::apollo::common::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::common::Header&>(
      ::apollo::common::_Header_default_instance_);
}
inline const ::apollo::common::Header& PointCloudRefine::header() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.header)
  return _internal_header();
}
inline void PointCloudRefine::unsafe_arena_set_allocated_header(
    ::apollo::common::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.drivers.PointCloudRefine.header)
}
inline ::apollo::common::Header* PointCloudRefine::release_header() {
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::apollo::common::Header* PointCloudRefine::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloudRefine.header)
  _has_bits_[0] &= ~0x00000002u;
  ::apollo::common::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::apollo::common::Header* PointCloudRefine::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000002u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::apollo::common::Header* PointCloudRefine::mutable_header() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudRefine.header)
  return _internal_mutable_header();
}
inline void PointCloudRefine::set_allocated_header(::apollo::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloudRefine.header)
}

// optional string frame_id = 2;
inline bool PointCloudRefine::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PointCloudRefine::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void PointCloudRefine::clear_frame_id() {
  frame_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PointCloudRefine::frame_id() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.frame_id)
  return _internal_frame_id();
}
inline void PointCloudRefine::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudRefine.frame_id)
}
inline std::string* PointCloudRefine::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudRefine.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& PointCloudRefine::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void PointCloudRefine::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PointCloudRefine::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.drivers.PointCloudRefine.frame_id)
}
inline void PointCloudRefine::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.drivers.PointCloudRefine.frame_id)
}
inline void PointCloudRefine::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.drivers.PointCloudRefine.frame_id)
}
inline std::string* PointCloudRefine::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PointCloudRefine::release_frame_id() {
  // @@protoc_insertion_point(field_release:apollo.drivers.PointCloudRefine.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PointCloudRefine::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.drivers.PointCloudRefine.frame_id)
}

// optional bool is_dense = 3;
inline bool PointCloudRefine::_internal_has_is_dense() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PointCloudRefine::has_is_dense() const {
  return _internal_has_is_dense();
}
inline void PointCloudRefine::clear_is_dense() {
  is_dense_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool PointCloudRefine::_internal_is_dense() const {
  return is_dense_;
}
inline bool PointCloudRefine::is_dense() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.is_dense)
  return _internal_is_dense();
}
inline void PointCloudRefine::_internal_set_is_dense(bool value) {
  _has_bits_[0] |= 0x00000004u;
  is_dense_ = value;
}
inline void PointCloudRefine::set_is_dense(bool value) {
  _internal_set_is_dense(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudRefine.is_dense)
}

// repeated .apollo.drivers.PointXYZIT point = 4;
inline int PointCloudRefine::_internal_point_size() const {
  return point_.size();
}
inline int PointCloudRefine::point_size() const {
  return _internal_point_size();
}
inline void PointCloudRefine::clear_point() {
  point_.Clear();
}
inline ::apollo::drivers::PointXYZIT* PointCloudRefine::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.drivers.PointCloudRefine.point)
  return point_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >*
PointCloudRefine::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.drivers.PointCloudRefine.point)
  return &point_;
}
inline const ::apollo::drivers::PointXYZIT& PointCloudRefine::_internal_point(int index) const {
  return point_.Get(index);
}
inline const ::apollo::drivers::PointXYZIT& PointCloudRefine::point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.point)
  return _internal_point(index);
}
inline ::apollo::drivers::PointXYZIT* PointCloudRefine::_internal_add_point() {
  return point_.Add();
}
inline ::apollo::drivers::PointXYZIT* PointCloudRefine::add_point() {
  // @@protoc_insertion_point(field_add:apollo.drivers.PointCloudRefine.point)
  return _internal_add_point();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::drivers::PointXYZIT >&
PointCloudRefine::point() const {
  // @@protoc_insertion_point(field_list:apollo.drivers.PointCloudRefine.point)
  return point_;
}

// optional double measurement_time = 5;
inline bool PointCloudRefine::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool PointCloudRefine::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void PointCloudRefine::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double PointCloudRefine::_internal_measurement_time() const {
  return measurement_time_;
}
inline double PointCloudRefine::measurement_time() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.measurement_time)
  return _internal_measurement_time();
}
inline void PointCloudRefine::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000010u;
  measurement_time_ = value;
}
inline void PointCloudRefine::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudRefine.measurement_time)
}

// optional fixed32 width = 6;
inline bool PointCloudRefine::_internal_has_width() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool PointCloudRefine::has_width() const {
  return _internal_has_width();
}
inline void PointCloudRefine::clear_width() {
  width_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudRefine::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudRefine::width() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.width)
  return _internal_width();
}
inline void PointCloudRefine::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  width_ = value;
}
inline void PointCloudRefine::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudRefine.width)
}

// optional fixed32 height = 7;
inline bool PointCloudRefine::_internal_has_height() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool PointCloudRefine::has_height() const {
  return _internal_has_height();
}
inline void PointCloudRefine::clear_height() {
  height_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudRefine::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PointCloudRefine::height() const {
  // @@protoc_insertion_point(field_get:apollo.drivers.PointCloudRefine.height)
  return _internal_height();
}
inline void PointCloudRefine::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  height_ = value;
}
inline void PointCloudRefine::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:apollo.drivers.PointCloudRefine.height)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace drivers
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pointcloud_2eproto
